import "@/styles/globals.css";
import type { Metadata } from "next";
import Header from "@/components/layout/Header";
import MainWrap from "@/components/layout/MainWrap";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Header />
        <MainWrap>{children}</MainWrap>
        <footer>[footer]</footer>
      </body>
    </html>
  );
}
